### ISSUE TITLE
Failed to activate the linter-eslint package

### ISSUE THREAD

**Issue by orlin** [AtomLinter/linter-js-yaml#23]
This started showing after I upgraded all my atom packages today.

**Atom Version**: 1.2.3
**System**: Mac OS X 10.10.5
**Thrown From**: [linter-js-yaml](https://github.com/AtomLinter/linter-js-yaml) package, v1.2.3

### Stack Trace

Failed to activate the linter-eslint package

```
At require(...)(...)[1].getFileName is not a function

TypeError: require(...)(...)[1].getFileName is not a function
    at Object.install (/Users/om/.atom/packages/linter-js-yaml/node_modules/atom-package-deps/lib/main.js:15:47)
    at Object.activate (/Users/om/.atom/packages/linter-eslint/lib/main.js:53:34)
    at Package.module.exports.Package.activateNow (/Applications/_Development_/Atom.app/Contents/Resources/app.asar/src/package.js:170:19)
    at /Applications/_Development_/Atom.app/Contents/Resources/app.asar/src/package.js:150:32
    at Package.module.exports.Package.measure (/Applications/_Development_/Atom.app/Contents/Resources/app.asar/src/package.js:92:15)
    at /Applications/_Development_/Atom.app/Contents/Resources/app.asar/src/package.js:143:26
    at Package.module.exports.Package.activate (/Applications/_Development_/Atom.app/Contents/Resources/app.asar/src/package.js:140:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/_Development_/Atom.app/Contents/Resources/app.asar/src/package-manager.js:512:21)
    at /Applications/_Development_/Atom.app/Contents/Resources/app.asar/src/package-manager.js:495:29
    at Config.module.exports.Config.transact (/Applications/_Development_/Atom.app/Contents/Resources/app.asar/src/config.js:311:16)
    at PackageManager.module.exports.PackageManager.activatePackages (/Applications/_Development_/Atom.app/Contents/Resources/app.asar/src/package-manager.js:490:19)
    at PackageManager.module.exports.PackageManager.activate (/Applications/_Development_/Atom.app/Contents/Resources/app.asar/src/package-manager.js:474:46)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/Applications/_Development_/Atom.app/Contents/Resources/app.asar/src/atom-environment.js:671:21)
    at Object.<anonymous> (/Applications/_Development_/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:38:8)
    at Object.<anonymous> (/Applications/_Development_/Atom.app/Contents/Resources/app.asar/src/initialize-application-window.js:49:4)
    at Module._compile (module.js:434:26)
    at Object.defineProperty.value [as .js] (/Applications/_Development_/Atom.app/Contents/Resources/app.asar/src/compile-cache.js:190:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at setupWindow (file:///Applications/_Development_/Atom.app/Contents/Resources/app.asar/static/index.js:79:5)
    at window.onload (file:///Applications/_Development_/Atom.app/Contents/Resources/app.asar/static/index.js:35:9)
```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "polymorph-ui",
      "duotone-light-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
Parinfer, v0.8.1
api-workbench, v0.8.6
autocomplete-paths, v1.0.2
clipboard-plus, v0.5.1
duotone-light-syntax, v0.3.2
file-icons, v1.6.12
fonts, v1.0.0
git-diff-details, v0.21.0
git-log, v0.4.1
highlight-column, v0.5.0
highlight-line, v0.11.0
highlight-selected, v0.11.1
language-elm, v1.3.0
linter, v1.11.2
linter-coffeelint, v1.1.2
linter-eslint, v5.2.1
linter-js-yaml, v1.2.3
linter-jscs, v3.2.0
linter-jsonlint, v1.0.1
linter-jsxhint, v0.1.2
linter-sass-lint, v0.4.1
lisp-paredit, v0.5.1
live-archive, v0.1.15
mac-fix-path, v0.0.0
minimap, v4.16.1
minimap-bookmarks, v0.1.0
minimap-find-and-replace, v4.3.2
minimap-git-diff, v4.1.8
minimap-highlight-selected, v4.3.1
minimap-pigments, v0.1.7
minimap-selection, v4.3.1
pigments, v0.19.0
polymorph-ui, v1.8.8
project-manager, v2.6.5
symbols-tree-view, v0.10.1
theme-switcher, v1.1.0
travis-ci-status, v0.18.0
tree-view-git-status, v0.2.2
vim-mode, v0.63.0
vim-mode-clipboard-plus, v0.1.0

# Dev
No dev packages
```

**Comment by steelbrain** [comment]
Fixed by https://github.com/steelbrain/package-deps/pull/31

Here's what you can do to make it work on your installation
```
cd ~/.atom/packages/linter-js-yaml
rm -rf node_modules/atom-package-deps
npm install atom-package-deps@latest
```

**Comment by orlin** [comment]
Thanks for the quick response.  I saw that new versions came out too.  Everything works again.
