### ISSUE TITLE
linter-js-yaml installation failed on Ubuntu 22.04.1

### ISSUE THREAD

**Issue by OdedViner** [AtomLinter/linter-js-yaml#277]
```
$ apm clean
Removing extraneous modules ✓
oded@ubuntu-vm2:~/test-project$ apm install linter-js-yaml
Installing linter-js-yaml to /home/oded/.atom/packages /usr/share/atom/resources/app/apm/lib/install.js:256
          if (body.releases.latest) {
                            ^

TypeError: Cannot read property 'latest' of undefined
    at /usr/share/atom/resources/app/apm/lib/install.js:256:29
    at Request._callback (/usr/share/atom/resources/app/apm/lib/request.js:57:22)
    at Request.self.callback (/usr/share/atom/resources/app/apm/node_modules/request/request.js:185:22)
    at Request.emit (events.js:223:5)
    at Request.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/request/request.js:1154:10)
    at Request.emit (events.js:223:5)
    at IncomingMessage.<anonymous> (/usr/share/atom/resources/app/apm/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (events.js:312:28)
    at IncomingMessage.emit (events.js:228:7)
    at endReadableNT (_stream_readable.js:1185:12)
```

```
$ cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.1 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.1 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
```

**Comment by AntoineGGG** [comment]
Same on fedora 37
