### ISSUE TITLE
Cannot read property 'line' of undefined

### ISSUE THREAD

**Issue by curtisblackwell** [AtomLinter/linter-js-yaml#8]
Getting this error on Atom 1.0.0 and linter-js-yaml 1.1.1:

```
TypeError: Cannot read property 'line' of undefined
  at Object.provider.processMessage (/Users/curtisblackwell/.atom/packages/linter-js-yaml/lib/linter-js-yaml.coffee:13:30)
  at /Users/curtisblackwell/.atom/packages/linter-js-yaml/lib/linter-js-yaml.coffee:27:36
  at Object.provider.lint (/Users/curtisblackwell/.atom/packages/linter-js-yaml/lib/linter-js-yaml.coffee:21:20)
  at /Users/curtisblackwell/.atom/packages/linter/lib/editor-linter.coffee:85:24
  at /Users/curtisblackwell/.atom/packages/linter/lib/editor-linter.coffee:84:25
  at Set.forEach (native)
  at EditorLinter.triggerLinters (/Users/curtisblackwell/.atom/packages/linter/lib/editor-linter.coffee:78:26)
  at EditorLinter.lint (/Users/curtisblackwell/.atom/packages/linter/lib/editor-linter.coffee:72:18)
  at Commands.lint (/Users/curtisblackwell/.atom/packages/linter/lib/commands.coffee:36:40)
  at /Users/curtisblackwell/.atom/packages/linter/lib/linter-plus.coffee:33:17
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/pane-container.js:343:34
  at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
  at Pane.module.exports.Pane.setActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:234:22)
  at Pane.module.exports.Pane.activateItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:298:21)
  at /Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:479:16
  at _fulfilled (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:794:54)
  at self.promiseDispatch.done (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:823:30)
  at Promise.promise.promiseDispatch (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:756:13)
  at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:564:44
  at flush (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/q/q.js:110:17)
  at process._tickCallback (node.js:357:13)
```

It's every time I open a YAML file (or whatever else triggers a lint).

**Comment by steelbrain** [comment]
Closing as it's been fixed by the rewrite
